### ISSUE TITLE
/project/custom/reflowSkin/pages/index@project-id="$artifactId" doesn't work as advertised.

### ISSUE THREAD

**Issue by christian-schlichtherle** [andriusvelykis/reflow-maven-skin#27]
Filtering a module by it's artifactId doesn't quite work because the test seems to use the given project-id as starting characters only. Consider this example:

```
<project>
    <custom>
        <reflowSkin>
            <pages>
                <index project-id="xyz">
                    <shortTitle>Welcome</shortTitle>
                    <breadcrumbs>false</breadcrumbs>
                </index>
            </pages>
        </reflowSkin>
    </custom>
</project>
```

Now consider if the submodules are named "xyz-api", "xyz-impl" etc then the configuration would be applied to them all.

**Comment by andriusvelykis** [comment]
The attribute is `project`, not `project-id`.

Assuming this is a typo in the issue report - is this what is really happening with your project? Because the code checks the `project` attribute value to be equal to the "slug" of the current project name - see [line 200 at SkinConfigTool](https://github.com/andriusvelykis/reflow-maven-skin/blob/91154d7ae815bc622068ed6a9358e627dd9a1149/reflow-velocity-tools/src/main/java/lt/velykis/maven/skins/reflow/SkinConfigTool.java#L200).

Do you have a reproducible example? Thanks!

**Comment by christian-schlichtherle** [comment]
Interesting. As said, I do get this weird behavior with the configuration as explained above. However, when I follow your advice and use the attribute name `project`instead of `project-id`, then it works as advertised. I suppose the code ignores the invalid attribute name and thus the element applies to _all_ pages named `index.*`, right?

I got the attribute name from the documentation of this project, so may I suggest to update the documentation? You might even want to display an error message on any invalid attribute name.

**Comment by andriusvelykis** [comment]
Yea, if the code does not find the `project` attribute, per-project filtering does not happen and the element applies to all these pages. Supporting warnings for invalid attribute names would be quite a bit of additional work, though :)

Where in the documentation did you get this from? I gave a look at the source code and documentation and I did not find any `project-id` attributes used..

**Comment by christian-schlichtherle** [comment]
Sorry, I can't figure out anymore where I got the invalid attribute name `project-id` from.
