### ISSUE TITLE
Suggestion: provide offline access to the bootstrap stylesheets.

### ISSUE THREAD

**Issue by runeflobakk** [andriusvelykis/reflow-maven-skin#3]
Quickly tried out the simplest use case (adding skin artifact to site.xml and adding the two deps to maven-site-plugin), and noticed that it produces a site which requires online access to http://netdna.bootstrapcdn.com.

Given that this plugin may also be valuable to closed corporate networks without Internet access, maybe the plugin should provide the two bootstrap stylesheets (bootstrap.min.css and bootstrap-responsive.min.css) and deploy them together with the rest of the site?

The skin looks very promising! Awesome work!

**Comment by andriusvelykis** [comment]
Thanks for the comments - I appreciate that.

The issue you mention is actually supported by Reflow skin. You can use the `<theme>site</theme>` option to achieve that. With `site` option, the skin expects Bootstrap CSS to be available in the _/css_ and _/js_ directories of your project site directory. This allows the user to use either default Bootstrap CSS files locally or customise them and use the custom CSS/JavaScript config. See theme config for more info:

http://andriusvelykis.github.com/reflow-maven-skin/skin/themes/

I chose the CDN delivery as default to improve the loading of such skins, but the local-CSS option is there.

Make sure to turn on absolute resource URLs when setting up `site` theme for multi-module projects. Otherwise you will have to add the Bootstrap CSS and JavaScript files into every module. See here for more details: 

http://andriusvelykis.github.com/reflow-maven-skin/skin/multi-module.html#Reuse_resources

I think this gives a working option to solve the issue you mentioned and avoids the need to distribute Bootstrap CSS files for all other uses of skin.

**Comment by andriusvelykis** [comment]
Closing the issue - reopen it if you think improvement is needed. Thanks!

**Comment by andriusvelykis** [comment]
Sorry for dismissing this earlier. This now has been implemented using the `<localResources>` tag, see #24.
